### PR TITLE
FEAT: Added feedback form link to footer.

### PR DESCRIPTION
**Pull request by Dev-Jordan-Schwartz**
General footer formatting/added a hyperlink for the feedback form.

### CODE REVIEW

**Review by logicalmic — CHANGES_REQUESTED** [review]
Jordan found a visual bug when the "Manual Inputs" are expanded. Please fix before merging.

**Comment by Dev-Jordan-Schwartz** [comment]
Made adjustments to footer/page formatting.

**Comment by logicalmic** [comment]
Looks good to us!

**Review by logicalmic — APPROVED** [review]

**Review by Applehand — APPROVED** [review]
looks good to me

**Pull request merged**
